# Note: don't use this config for your own repositories. Instead, see
# "Version control integration" in docs/integrations/source_version_control.md
exclude: ^(profiling/|tests/data/)
repos:
  - repo: local
    

      

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify
        exclude: ^src/blib2to3/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        exclude: ^docs/conf.py
        additional_dependencies:
          - types-PyYAML
          - tomli >= 0.2.6, < 2.0.0
          - click >= 8.1.0, != 8.1.4, != 8.1.5
          - packaging >= 22.0
          - platformdirs >= 2.1.0
          - pytest
          - hypothesis

