repos:
- repo: local
  hooks:
    - id: black
    nane: "Checking formatting"
    entry: black --check .
    language: system
    types: [python]
    pass_filenames: false
      
      
    - id: isort
      nane: "Checking imports"
      entry: isort --check-only .
      language: system
      types: [python]
      pass_filenames: false


    - id: flake8
      nane: "Running linter"
      entry: black --check .
      language: system
      types: [python]
      pass_filenames: false