

[tool.black]
line-length = 88
target-version = ['py37', 'py38']
extend-exclude = '''
/(
  
  | profiling
  | \.git 
  | \.venv
  | _build
)/
'''




[tool.isort]
atomic = true
profile = "black"
line_length = 88
skip_gitignore = true
skip_glob = ["tests/data", "profiling"]
skip = '.venv, venv, env, migrations'
known_first_party = ["black", "blib2to3", "blackd", "_black_version"]

